### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by silaskoehler** [ludohenin/ng2-wp-blog#8] opened 2016-08-20 12:12 UTC
hi,

the code looks great, but when i try to start the app ("npm start") i got the following errors:

> [14:07:39] Starting 'build.js.dev'...
> src/blog/post/post.component.ts(19,17): error TS2315: Type 'Subscription' is not generic.
> src/blog/posts/posts.component.ts(21,17): error TS2315: Type 'Subscription' is not generic.
> src/blog/services/wp/terms.ts(27,14): error TS2415: Class 'CategoryModel' incorrectly extends base class 'WpModel'.
>   Types of property 'parent' are incompatible.
>     Type 'number' is not assignable to type 'WpCollection<WpModel>'.
> src/blog/services/wp/terms.ts(40,56): error TS2344: Type 'CategoryModel' does not satisfy the constraint 'WpModel'.
>   Types of property 'parent' are incompatible.
>     Type 'number' is not assignable to type 'WpCollection<WpModel>'.
> [14:07:43] TypeScript: 4 semantic errors
> [14:07:43] TypeScript: emit succeeded (with errors)

what am I doing wrong?

**Comment by ludohenin** [comment] 2016-08-20 14:22
This is a duplicate of #4 
You're not doing anything wrong :-)

**Closed as completed by ludohenin** 2016-08-20 14:22 UTC
