### ISSUE TITLE
How to Start?

### ISSUE THREAD

**Issue by smyth64** [ludohenin/ng2-wp-blog#7] opened 2016-05-25 17:39 UTC
Hi,
When I run "npm start", I get the following errors.

```
[21:15:01] Starting 'build.js.dev'...
src/blog/post/post.component.ts(19,17): error TS2315: Type 'Subscription' is not generic.
src/blog/posts/posts.component.ts(21,17): error TS2315: Type 'Subscription' is not generic.
src/blog/services/wp/terms.ts(27,14): error TS2415: Class 'CategoryModel' incorrectly extends base class 'WpModel'.
  Types of property 'parent' are incompatible.
    Type 'number' is not assignable to type 'WpCollection<WpModel>'.
src/blog/services/wp/terms.ts(40,56): error TS2344: Type 'CategoryModel' does not satisfy the constraint 'WpModel'.
  Types of property 'parent' are incompatible.
    Type 'number' is not assignable to type 'WpCollection<WpModel>'
[21:15:07] TypeScript: 4 semantic errors
```

**Comment by ludohenin** [comment] 2016-05-25 19:47
@smith64fx Yes I know. There are types errors but the compiler emits successfully. I don't have much time to work on this so ... if you have time, i'd be very pleased to see a PR :-)
This is actually a duplicate of #4

**Closed as completed by ludohenin** 2016-05-25 19:47 UTC

**Comment by smyth64** [comment] 2016-05-25 21:10
Thank you.
Can you tell us which version of node and typings you are using?

**Comment by ludohenin** [comment] 2016-05-25 22:09
I think the seed this project is based of needs node 4+, npm 3+ and typings `"typings": "^0.6.8",`
